"""Backlinks generator — scan all wiki pages for [[wikilinks]], build adjacency map."""

from __future__ import annotations

import re
from collections import defaultdict

from shared.python.manfriday_core.gcs import read_text, list_markdown_files, user_path
from workers.compile.write_guard import guarded_write_text

WIKILINK_PATTERN = re.compile(r"\[\[([^\]]+)\]\]")


def rebuild_backlinks(user_id: str) -> dict[str, list[str]]:
    """Scan all wiki/**/*.md for [[wikilinks]] and regenerate backlinks.md.

    Returns:
        Dict mapping page name → list of pages that link to it
    """
    wiki_prefix = user_path(user_id, "wiki")
    all_files = list_markdown_files(wiki_prefix + "/")

    # Forward links: source → [targets]
    forward: dict[str, list[str]] = {}
    # Backward links: target → [sources]
    backward: defaultdict[str, list[str]] = defaultdict(list)

    for filepath in all_files:
        # Skip structural files
        filename = filepath.split("/")[-1].replace(".md", "")
        if filename in ("index", "log", "backlinks", "lint_queue"):
            continue

        try:
            content = read_text(filepath)
        except Exception:
            continue

        links = WIKILINK_PATTERN.findall(content)
        forward[filename] = list(set(links))

        for link in set(links):
            backward[link].append(filename)

    # Generate backlinks.md
    lines = [
        "# Backlinks",
        "",
        "Bidirectional [[wikilink]] adjacency map. Auto-generated by compile worker.",
        "",
    ]

    for target in sorted(backward.keys()):
        sources = sorted(set(backward[target]))
        source_links = ", ".join(f"[[{s}]]" for s in sources)
        lines.append(f"- **[[{target}]]** ← {source_links}")

    content = "\n".join(lines) + "\n"
    backlinks_path = user_path(user_id, "wiki", "backlinks.md")
    guarded_write_text(user_id, backlinks_path, content)

    return dict(backward)
